name = "compute-toys"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"
kv_namespaces = [
  { binding = "__NEXT_ON_PAGES__KV_SUSPENSE_CACHE", id = "6c06679849bf4533bfde274c3a08282e" }
]

[placement]
mode = "smart"
