name = "compute-toys"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
kv_namespaces = [
  { binding = "__NEXT_ON_PAGES__KV_SUSPENSE_CACHE", id = "6c06679849bf4533bfde274c3a08282e" }
]
