name: CloudFlare Pages
on:
#   push:
#     branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    # Allow GITHUB_TOKEN to write deployments for my action (https://docs.github.com/en/actions/security-guides/automatic-token-authentication)
    permissions:
      contents: read
      deployments: write
    steps:
    - run: echo Deploying ${{ github.event.pull_request.head.sha }}
    - name: Await CF Pages
      id: cf-pages
      uses: WalshyDev/cf-pages-await@v1
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        project: 'compute-toys'
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        commitHash: ${{ github.event.pull_request.head.sha }}
    - run: echo Deployed ${{ steps.cf-pages.outputs.url }}
