name: Deploy
on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
  deployments: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: wgpu-compute-toy
      - run: cargo install wasm-pack --force
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'yarn'
      - run: yarn
      - run: yarn build
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
